version: "3.8"

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./data:/var/lib/mysql

  users:
    image: alpine:latest
    command: sh -c "mkdir -m 777 /structure && touch /structure/sync-work && touch /structure/nobody-work && adduser -D -u 5000 collin"
